app:
  description: Product Service
  version: v1.0.0

logging:
  level:
    org:
      hibernate:
        # stat: debug
        # type: trace
management:
  endpoints:
    web:
      exposure:
        include: mappings

server:
  forward-headers-strategy: framework
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    # jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    url: jdbc:mysql://localhost:3306/product_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create database schema from SQL files
      # https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java
      # create, create-drop, validate, and update
      ddl-auto: update
      naming:
        physical-strategy: bdd.demo.ecommerce.utils.CustomPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    show-sql: true
  main:
    banner-mode: CONSOLE
  output:
    ansi:
      enabled: ALWAYS
